export type EnvConfig = {
  NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY: string;
  NEXT_PUBLIC_VAPID_PUBLIC_KEY: string;
  NEXT_PUBLIC_VAPID_PRIVATE_KEY: string;
  NEXT_PUBLIC_API_ENDPOINT_URL: string;
  NEXT_PUBLIC_WEB_URL: string;
};
