import { Initializer, RecoilRootWrapper } from '@components/app';

import { ModalWrapper } from '@web-core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import React from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={inter.className}>
        <Script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.1/kakao.js"
          integrity="sha384-pwDTu8wHS3HUfAgCS+FIgpFJHUJNO/2Eb0MZpYolcWKKVSQ6PDdeuEiwo/a1qdzq"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
          rel="preload"
        />
        <React.StrictMode>
          <RecoilRootWrapper>
            <Initializer />
            <ModalWrapper>{children}</ModalWrapper>
          </RecoilRootWrapper>
        </React.StrictMode>
      </body>
    </html>
  );
}
