import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StyledComponentsRegistry } from "@web-core";
import { ThemeProvider } from "@contexts";
import Script from "next/script";
import { Head } from "next/document";
import { KakaoInit } from "@components/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <KakaoInit>{children}</KakaoInit>
          </ThemeProvider>
        </StyledComponentsRegistry>
        <Script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.1/kakao.min.js"
          integrity="sha384-kDljxUXHaJ9xAb2AzRd59KxjrFjzHa5TAoFQ6GbYTCAG0bjM55XohjjDT7tDDC01"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
